import { secureApiRoute, apiError } from '@/lib/security/api-protection';
import { NextResponse } from 'next/server';

function padTime(t: string): string {
    // Ensure HH:MM:SS format
    if (t.length === 5) return t + ':00';
    return t;
}

function toICSDateTime(date: string, time: string): string {
    // Convert "2026-04-22" + "14:30" to "20260422T143000"
    const d = date.replace(/-/g, '');
    const t = padTime(time).replace(/:/g, '');
    return `${d}T${t}`;
}

function escapeICS(text: string): string {
    return text.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');
}

export const GET = secureApiRoute(
    async (context) => {
        const { userId, supabase } = context;
        const { searchParams } = new URL(context.request.url);
        const date = searchParams.get('date') || new Date().toISOString().split('T')[0];

        // Fetch blocks for the given date
        const { data: blocks, error } = await supabase
            .from('schedule_blocks')
            .select('*')
            .eq('user_id', userId)
            .eq('date', date)
            .order('start_time');

        if (error) {
            return apiError('Failed to fetch schedule', 500);
        }

        if (!blocks || blocks.length === 0) {
            return apiError('No schedule blocks found for this date', 404);
        }

        // Build ICS file
        const events = blocks.map((block: any) => {
            const uid = `${block.id}@plannrai.app`;
            const dtStart = toICSDateTime(date, block.start_time);
            const dtEnd = toICSDateTime(date, block.end_time);
            const summary = escapeICS(block.title || block.block_type || 'Block');
            const description = escapeICS(block.description || `${block.block_type} block generated by PlannrAI`);

            return [
                'BEGIN:VEVENT',
                `UID:${uid}`,
                `DTSTART:${dtStart}`,
                `DTEND:${dtEnd}`,
                `SUMMARY:${summary}`,
                `DESCRIPTION:${description}`,
                `CATEGORIES:${block.block_type?.toUpperCase() || 'BLOCK'}`,
                'STATUS:CONFIRMED',
                'END:VEVENT',
            ].join('\r\n');
        });

        const icsContent = [
            'BEGIN:VCALENDAR',
            'VERSION:2.0',
            'PRODID:-//PlannrAI//Schedule//EN',
            'CALSCALE:GREGORIAN',
            'METHOD:PUBLISH',
            `X-WR-CALNAME:PlannrAI Schedule ${date}`,
            ...events,
            'END:VCALENDAR',
        ].join('\r\n');

        return new NextResponse(icsContent, {
            headers: {
                'Content-Type': 'text/calendar; charset=utf-8',
                'Content-Disposition': `attachment; filename="plannrai-${date}.ics"`,
            },
        });
    },
    { requireAuth: true, auditAction: 'calendar_export' }
);
