-- MIGRATION: Superintelligence Core Infrastructure
-- GOAL: Establish System Memory (UserContext) and Thinking Layer (Interventions)

BEGIN;

-- 1. User Context (Long-term Memory)
-- Stores facts, preferences, and recurring patterns learned by the AI.
CREATE TABLE IF NOT EXISTS public.user_context (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Category of context
    type TEXT NOT NULL CHECK (type IN ('fact', 'preference', 'pattern', 'constraint')),
    
    -- The core content
    content TEXT NOT NULL,
    
    -- Derived metadata
    source TEXT, -- 'brain_dump', 'behavior', 'profile', 'manual'
    confidence FLOAT DEFAULT 0.5, -- 0.0 to 1.0
    
    -- Expiry/Relevance metadata
    last_used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. AI Interventions (Proactive Nudges)
-- Stores autonomous suggestions generated by the ThinkingService.
CREATE TABLE IF NOT EXISTS public.ai_interventions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Intervention Type
    type TEXT NOT NULL CHECK (type IN ('stagnation', 'burnout', 'pivot', 'win_streak', 'optimization')),
    
    -- Content to display
    message TEXT NOT NULL,
    
    -- Actionable Payload (e.g., a schedule patch)
    payload JSONB DEFAULT '{}'::jsonb,
    
    -- Interaction State
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'dismissed', 'ignored')),
    
    action_taken_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_context_lookup ON public.user_context(user_id, type);
CREATE INDEX IF NOT EXISTS idx_interventions_pending ON public.ai_interventions(user_id, status) WHERE status = 'pending';

-- Enable RLS
ALTER TABLE public.user_context ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_interventions ENABLE ROW LEVEL SECURITY;

-- Basic RLS Policies
DROP POLICY IF EXISTS "Users can view their own context" ON public.user_context;
CREATE POLICY "Users can view their own context" ON public.user_context
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own interventions" ON public.ai_interventions;
CREATE POLICY "Users can view their own interventions" ON public.ai_interventions
    FOR ALL USING (auth.uid() = user_id);

COMMIT;
