import { createClient } from '@/lib/supabase/server';
import { SupabaseClient } from '@supabase/supabase-js';
import { addDays, startOfDay, addMinutes, format, parseISO, isSameDay } from 'date-fns';
import { ScheduleBlock, Profile } from '@/types/database';

interface OptimizationContext {
    lockedBlocks: ScheduleBlock[];
    flexibleBlocks: ScheduleBlock[];
    profile: Profile;
}

export class OptimiseWeekService {
    static async optimiseWeek(userId: string, startDate: Date, supabase: SupabaseClient) {
        // 1. Fetch Schedule & Profile
        const startStr = format(startDate, 'yyyy-MM-dd');
        const endStr = format(addDays(startDate, 6), 'yyyy-MM-dd');

        const { data: blocks } = await supabase
            .from('schedule_blocks')
            .select('*')
            .eq('user_id', userId)
            .gte('date', startStr)
            .lte('date', endStr);

        const { data: profile } = await supabase.from('profiles').select('*').eq('id', userId).single();

        if (!blocks || blocks.length === 0 || !profile) {
            return { patch: { changes: [] }, summary: { optimized_count: 0 } };
        }

        // 2. Classify Blocks
        // Locked: Fixed by user, Anchors (commitments), or Generated Meals/Sleep (if we had them as blocks)
        // We assume "Meals" generated by PlanWeek have is_fixed=true or is_locked=true? 
        // PlanWeek sets Meals as is_fixed=true.

        const lockedBlocks = blocks.filter(b => b.is_fixed || b.is_locked || b.commitment_id);
        const flexibleBlocks = blocks.filter(b => !b.is_fixed && !b.is_locked && !b.commitment_id);

        const ctx: OptimizationContext = {
            lockedBlocks,
            flexibleBlocks,
            profile
        };

        const patches: any[] = [];
        let optimizedCount = 0;

        // 3. Optimization Logic: Resolve Conflicts
        // Iterate through flexible blocks. If they overlap with *anything* (Locked or other Flexible), move them.

        // We sort everything by time first to process generally chronologically.
        // Actually, we should process Flexible blocks priority? Or just time.
        flexibleBlocks.sort((a, b) => {
            if (a.date !== b.date) return a.date.localeCompare(b.date);
            return a.start_time.localeCompare(b.start_time);
        });

        // We maintain a "simulated state" of where blocks are currently placed.
        // Initially, it matches DB.
        const simulation = [...lockedBlocks, ...flexibleBlocks];

        for (const flexBlock of flexibleBlocks) {
            // Check for collisions
            if (this.hasCollision(flexBlock, simulation)) {
                // Find next free slot
                const newSlot = this.findNextFreeSlot(flexBlock, simulation, ctx.profile);

                if (newSlot) {
                    // Update Simulation
                    flexBlock.start_time = newSlot.start;
                    flexBlock.end_time = newSlot.end;
                    flexBlock.date = newSlot.date;

                    // Create Patch
                    patches.push({
                        op: 'update_event',
                        event_id: flexBlock.id,
                        payload: {
                            start_time: newSlot.start,
                            end_time: newSlot.end,
                            date: newSlot.date
                        },
                        reason: 'Resolved Overlap'
                    });
                    optimizedCount++;
                } else {
                    // Could not fit! Mark as unscheduled? or leave colliding?
                    console.warn(`Could not optimize block ${flexBlock.title}`);
                }
            }
        }

        return {
            patch: {
                undoable: true,
                changes: patches
            },
            summary: {
                optimized_blocks: optimizedCount
            }
        };
    }

    private static hasCollision(target: ScheduleBlock, allBlocks: ScheduleBlock[]): boolean {
        // Check collision with ANY other block (excluding itself)
        const tStart = this.toMins(target.start_time);
        const tEnd = this.toMins(target.end_time);

        return allBlocks.some(other => {
            if (other.id === target.id) return false;
            if (other.date !== target.date) return false;

            const oStart = this.toMins(other.start_time);
            const oEnd = this.toMins(other.end_time);

            return tStart < oEnd && tEnd > oStart;
        });
    }

    private static findNextFreeSlot(
        block: ScheduleBlock,
        allBlocks: ScheduleBlock[],
        profile: Profile
    ): { date: string, start: string, end: string } | null {
        // Strategy: Look forward from current start time in 15 min increments
        // until we find a gap that fits duration.
        // Limit: End of day? Or push to next day? 
        // MVP: Stick to same day for now.

        const duration = this.toMins(block.end_time) - this.toMins(block.start_time);
        const searchDate = block.date;
        const searchStart = this.toMins(block.start_time);

        // Safety Break
        const maxTime = 23 * 60; // 11 PM

        // Scan allowed windows (e.g. not sleep)
        // Simpler: Just scan forward and check collisions.

        for (let time = searchStart; time + duration <= maxTime; time += 15) {
            const potentialStart = time;
            const potentialEnd = time + duration;

            // Check if this slot collides with any OTHER block
            const collision = allBlocks.some(other => {
                if (other.id === block.id) return false; // ignore self
                if (other.date !== searchDate) return false;

                const oStart = this.toMins(other.start_time);
                const oEnd = this.toMins(other.end_time);

                return potentialStart < oEnd && potentialEnd > oStart;
            });

            // Check Sleep Constraint
            // ...

            if (!collision) {
                return {
                    date: searchDate,
                    start: this.toTimeStr(potentialStart),
                    end: this.toTimeStr(potentialEnd)
                };
            }
        }

        return null;
    }

    private static toMins(t: string): number {
        const [h, m] = t.split(':').map(Number);
        return h * 60 + m;
    }

    private static toTimeStr(m: number): string {
        const h = Math.floor(m / 60);
        const min = m % 60;
        return `${h.toString().padStart(2, '0')}:${min.toString().padStart(2, '0')}:00`;
    }
}
